on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Debug
        run: ls /home/runner/work/; ls /home/runner/work/mdelhoneux.github.io/; ls /home/runner/work/mdelhoneux.github.io/mdelhoneux.github.io/; ls /home/runner/work/mdelhoneux.github.io/mdelhoneux.github.io/mdelhoneux.github.io;
      - name: Deploy with rsync
        run: rsync -avz _site/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/staff/miryam/public_html/
